package io.github.solcott.marineapi.nav.ais

/**
 * Maritime Identification Digits to the administration the ITU assigned them to.
 *
 * The list published by the ITU under Recommendation ITU-R M.585, as an ordinary lookup rather than
 * an enum: the entries are data that changes when a state is admitted, renamed or split, and there
 * is nothing to switch on. Several administrations hold more than one MID -- the United States has
 * five and Panama twelve -- so this is many-to-one in that direction.
 *
 * **Territories are named separately from the state that administers them**, because that is how
 * the assignment works: the Faroe Islands hold 231 in their own right rather than sharing Denmark's
 * 219 and 220, and a target flying either is telling you something different. Where the parent is
 * not obvious from the name it is given in brackets.
 *
 * An unassigned MID is simply absent, which [Mmsi.flagState] reports as `null`. That is the right
 * answer for a range the ITU has not allocated and for one allocated since this table was written;
 * a wrong flag state would be worse than none.
 */
internal val MID_COUNTRIES: Map<Int, String> =
  mapOf(
    // Europe
    201 to "Albania",
    202 to "Andorra",
    203 to "Austria",
    204 to "Azores (Portugal)",
    205 to "Belgium",
    206 to "Belarus",
    207 to "Bulgaria",
    208 to "Vatican City",
    209 to "Cyprus",
    210 to "Cyprus",
    211 to "Germany",
    212 to "Cyprus",
    213 to "Georgia",
    214 to "Moldova",
    215 to "Malta",
    216 to "Armenia",
    218 to "Germany",
    219 to "Denmark",
    220 to "Denmark",
    224 to "Spain",
    225 to "Spain",
    226 to "France",
    227 to "France",
    228 to "France",
    229 to "Malta",
    230 to "Finland",
    231 to "Faroe Islands (Denmark)",
    232 to "United Kingdom",
    233 to "United Kingdom",
    234 to "United Kingdom",
    235 to "United Kingdom",
    236 to "Gibraltar (United Kingdom)",
    237 to "Greece",
    238 to "Croatia",
    239 to "Greece",
    240 to "Greece",
    241 to "Greece",
    242 to "Morocco",
    243 to "Hungary",
    244 to "Netherlands",
    245 to "Netherlands",
    246 to "Netherlands",
    247 to "Italy",
    248 to "Malta",
    249 to "Malta",
    250 to "Ireland",
    251 to "Iceland",
    252 to "Liechtenstein",
    253 to "Luxembourg",
    254 to "Monaco",
    255 to "Madeira (Portugal)",
    256 to "Malta",
    257 to "Norway",
    258 to "Norway",
    259 to "Norway",
    261 to "Poland",
    262 to "Montenegro",
    263 to "Portugal",
    264 to "Romania",
    265 to "Sweden",
    266 to "Sweden",
    267 to "Slovakia",
    268 to "San Marino",
    269 to "Switzerland",
    270 to "Czech Republic",
    271 to "Turkiye",
    272 to "Ukraine",
    273 to "Russian Federation",
    274 to "North Macedonia",
    275 to "Latvia",
    276 to "Estonia",
    277 to "Lithuania",
    278 to "Slovenia",
    279 to "Serbia",
    // The Americas and the Caribbean
    301 to "Anguilla (United Kingdom)",
    303 to "Alaska (United States)",
    304 to "Antigua and Barbuda",
    305 to "Antigua and Barbuda",
    306 to "Curacao, Sint Maarten and the Caribbean Netherlands",
    307 to "Aruba (Netherlands)",
    308 to "Bahamas",
    309 to "Bahamas",
    310 to "Bermuda (United Kingdom)",
    311 to "Bahamas",
    312 to "Belize",
    314 to "Barbados",
    316 to "Canada",
    319 to "Cayman Islands (United Kingdom)",
    321 to "Costa Rica",
    323 to "Cuba",
    325 to "Dominica",
    327 to "Dominican Republic",
    329 to "Guadeloupe (France)",
    330 to "Grenada",
    331 to "Greenland (Denmark)",
    332 to "Guatemala",
    334 to "Honduras",
    336 to "Haiti",
    338 to "United States",
    339 to "Jamaica",
    341 to "Saint Kitts and Nevis",
    343 to "Saint Lucia",
    345 to "Mexico",
    347 to "Martinique (France)",
    348 to "Montserrat (United Kingdom)",
    350 to "Nicaragua",
    351 to "Panama",
    352 to "Panama",
    353 to "Panama",
    354 to "Panama",
    355 to "Panama",
    356 to "Panama",
    357 to "Panama",
    358 to "Puerto Rico (United States)",
    359 to "El Salvador",
    361 to "Saint Pierre and Miquelon (France)",
    362 to "Trinidad and Tobago",
    364 to "Turks and Caicos Islands (United Kingdom)",
    366 to "United States",
    367 to "United States",
    368 to "United States",
    369 to "United States",
    370 to "Panama",
    371 to "Panama",
    372 to "Panama",
    373 to "Panama",
    374 to "Panama",
    375 to "Saint Vincent and the Grenadines",
    376 to "Saint Vincent and the Grenadines",
    377 to "Saint Vincent and the Grenadines",
    378 to "British Virgin Islands (United Kingdom)",
    379 to "United States Virgin Islands (United States)",
    // Asia
    401 to "Afghanistan",
    403 to "Saudi Arabia",
    405 to "Bangladesh",
    408 to "Bahrain",
    410 to "Bhutan",
    412 to "China",
    413 to "China",
    414 to "China",
    416 to "Taiwan",
    417 to "Sri Lanka",
    419 to "India",
    422 to "Iran",
    423 to "Azerbaijan",
    425 to "Iraq",
    428 to "Israel",
    431 to "Japan",
    432 to "Japan",
    434 to "Turkmenistan",
    436 to "Kazakhstan",
    437 to "Uzbekistan",
    438 to "Jordan",
    440 to "Republic of Korea",
    441 to "Republic of Korea",
    443 to "Palestine",
    445 to "Democratic People's Republic of Korea",
    447 to "Kuwait",
    450 to "Lebanon",
    451 to "Kyrgyzstan",
    453 to "Macao (China)",
    455 to "Maldives",
    457 to "Mongolia",
    459 to "Nepal",
    461 to "Oman",
    463 to "Pakistan",
    466 to "Qatar",
    468 to "Syria",
    470 to "United Arab Emirates",
    471 to "United Arab Emirates",
    472 to "Tajikistan",
    473 to "Yemen",
    475 to "Yemen",
    477 to "Hong Kong (China)",
    478 to "Bosnia and Herzegovina",
    // Oceania
    501 to "Adelie Land (France)",
    503 to "Australia",
    506 to "Myanmar",
    508 to "Brunei Darussalam",
    510 to "Micronesia",
    511 to "Palau",
    512 to "New Zealand",
    514 to "Cambodia",
    515 to "Cambodia",
    516 to "Christmas Island (Australia)",
    518 to "Cook Islands (New Zealand)",
    520 to "Fiji",
    523 to "Cocos (Keeling) Islands (Australia)",
    525 to "Indonesia",
    529 to "Kiribati",
    531 to "Laos",
    533 to "Malaysia",
    536 to "Northern Mariana Islands (United States)",
    538 to "Marshall Islands",
    540 to "New Caledonia (France)",
    542 to "Niue (New Zealand)",
    544 to "Nauru",
    546 to "French Polynesia (France)",
    548 to "Philippines",
    550 to "Timor-Leste",
    553 to "Papua New Guinea",
    555 to "Pitcairn Islands (United Kingdom)",
    557 to "Solomon Islands",
    559 to "American Samoa (United States)",
    561 to "Samoa",
    563 to "Singapore",
    564 to "Singapore",
    565 to "Singapore",
    566 to "Singapore",
    567 to "Thailand",
    570 to "Tonga",
    572 to "Tuvalu",
    574 to "Viet Nam",
    576 to "Vanuatu",
    577 to "Vanuatu",
    578 to "Wallis and Futuna Islands (France)",
    // Africa
    601 to "South Africa",
    603 to "Angola",
    605 to "Algeria",
    607 to "Saint Paul and Amsterdam Islands (France)",
    608 to "Ascension Island (United Kingdom)",
    609 to "Burundi",
    610 to "Benin",
    611 to "Botswana",
    612 to "Central African Republic",
    613 to "Cameroon",
    615 to "Congo",
    616 to "Comoros",
    617 to "Cabo Verde",
    618 to "Crozet Archipelago (France)",
    619 to "Cote d'Ivoire",
    620 to "Comoros",
    621 to "Djibouti",
    622 to "Egypt",
    624 to "Ethiopia",
    625 to "Eritrea",
    626 to "Gabon",
    627 to "Ghana",
    629 to "Gambia",
    630 to "Guinea-Bissau",
    631 to "Equatorial Guinea",
    632 to "Guinea",
    633 to "Burkina Faso",
    634 to "Kenya",
    635 to "Kerguelen Islands (France)",
    636 to "Liberia",
    637 to "Liberia",
    638 to "South Sudan",
    642 to "Libya",
    644 to "Lesotho",
    645 to "Mauritius",
    647 to "Madagascar",
    649 to "Mali",
    650 to "Mozambique",
    654 to "Mauritania",
    655 to "Malawi",
    656 to "Niger",
    657 to "Nigeria",
    659 to "Namibia",
    660 to "Reunion (France)",
    661 to "Rwanda",
    662 to "Sudan",
    663 to "Senegal",
    664 to "Seychelles",
    665 to "Saint Helena (United Kingdom)",
    666 to "Somalia",
    667 to "Sierra Leone",
    668 to "Sao Tome and Principe",
    669 to "Eswatini",
    670 to "Chad",
    671 to "Togo",
    672 to "Tunisia",
    674 to "Tanzania",
    675 to "Uganda",
    676 to "Democratic Republic of the Congo",
    677 to "Tanzania",
    678 to "Zambia",
    679 to "Zimbabwe",
    // South America
    701 to "Argentina",
    710 to "Brazil",
    720 to "Bolivia",
    725 to "Chile",
    730 to "Colombia",
    735 to "Ecuador",
    740 to "Falkland Islands (United Kingdom)",
    745 to "Guiana (France)",
    750 to "Guyana",
    755 to "Paraguay",
    760 to "Peru",
    765 to "Suriname",
    770 to "Uruguay",
    775 to "Venezuela",
  )
