#!/bin/bash
# PreToolUse hook (Edit|Write): guards two trees that must not be edited by hand.
#
# - marine-api/api/ is generated by `:marine-api:apiDump`. A hand edit makes apiCheck pass against
#   an ABI the code does not have, and it is the diff reviewers read for an API change.
# - jvmTest/resources/data/gpsd/ is a vendored BSD-2-Clause corpus that must stay byte for byte, and
#   whose README carries the licence notice. Adding a log is legitimate but rare, so this asks rather
#   than refuses.

command -v jq >/dev/null || exit 0
file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0

decide() {
  jq -n --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: $d, permissionDecisionReason: $r}}'
  exit 0
}

case "$file" in
*/marine-api/api/*.api | marine-api/api/*.api)
  decide deny "marine-api/api/ is generated. Change the public API in source, then run ./gradlew :marine-api:apiDump and read the resulting diff -- never edit the dump by hand."
  ;;
*/jvmTest/resources/data/gpsd/*)
  decide ask "This is the vendored gpsd conformance corpus (BSD-2-Clause, not LGPL). The logs and .chk files must stay byte for byte and the README notice must stay with them; adding a log moves every pinned corpus count. Approve only if this is intended."
  ;;
esac
exit 0
