[versions]
agp = "9.3.1"
androidx-activity = "1.11.0"
dokka = "2.2.0"
kotlin = "2.4.10"
junit = "4.13.2"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.0"
kotlinx-io = "0.8.0"
nrjavaserial = "5.2.1"
#noinspection UnusedVersionCatalogEntry
androidCompileSdk = "37"
#noinspection UnusedVersionCatalogEntry
androidMinSdk = "24"
#noinspection UnusedVersionCatalogEntry
jvm-toolchain = "25" # After updating run ./gradlew updateDaemonJvm
#noinspection UnusedVersionCatalogEntry
jvm-compat = "17"
ktfmt = "0.27.0"
sort-dependencies = "0.21.0"
publish = "0.37.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktfmt-gradle-plugin = { module = "com.ncorti.ktfmt.gradle:com.ncorti.ktfmt.gradle.gradle.plugin", version.ref = "ktfmt" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
nrjavaserial = { module = "com.neuronrobotics:nrjavaserial", version.ref = "nrjavaserial" }

[plugins]
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
sort-dependencies = { id = "com.squareup.sort-dependencies", version.ref = "sort-dependencies" }
